### ISSUE TITLE
https://openshift.org doesn't work

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/openshift.org#67]
Originally reported by @codificat in a mailing-list:

> There's an HTTP redirect in place for http://openshift.org to https://www.openshift.org. However, https://openshift.org doesn't work.
> 
>     pep@uio ~ $ curl -I http://openshift.org
>     HTTP/1.1 301 Moved Permanently
>     Server: nginx/1.6.2
>     Date: Fri, 10 Mar 2017 17:23:49 GMT
>     Content-Type: text/html
>     Content-Length: 184
>     Connection: keep-alive
>     Location: http://www.openshift.org//
> 
>     pep@uio ~ $ curl -I -m 5 https://openshift.org 
>     curl: (7) Failed to connect to openshift.org port 443: Connection timed out

As hinted by @jsvgoncalves, the configuration is in this file:
https://github.com/openshift/openshift.org/blob/master/source/.htaccess#L340-L341

**Comment by wgordon17** [comment]
I'm investigating this. Thanks for letting us know!

**Comment by jsvgoncalves** [comment]
@wgordon17 : @jiri-fiala has probably some interesting insights on what's happening

**Comment by coreydaley** [comment]
openshift.org points to a couple of servers that the Operations team uses for redirecting some sites
host openshift.org
openshift.org has address 216.146.46.11
openshift.org has address 216.146.46.10


www.openshift.org is a (probably) cname that points directly to the org-osdevelopers.rhcloud.com
host www.openshift.org
www.openshift.org is an alias for org-osdevelopers.rhcloud.com.
org-osdevelopers.rhcloud.com is an alias for ex-csm-node2.prod.rhcloud.com.
ex-csm-node2.prod.rhcloud.com is an alias for ec2-54-84-62-10.compute-1.amazonaws.com.
ec2-54-84-62-10.compute-1.amazonaws.com has address 54.84.62.10

The SSL certificate is only installed on the www which is hosted on openshift.  This is because you can't do a CNAME on a naked domain using our dns provider (or at least you couldn't before I think, which is/was a common problem for openshift).

**Comment by wgordon17** [comment]
@coreydaley is correct, that OpenShift does have that restriction because it relies on CNAME records, which can't point to naked domains.

Currently the http redirection is being handled by some "magic" functionality in DynDNS. DynDNS does not have the ability to redirect based on https, so at this point, there is no way to overcome this limitation. If you reference the naked openshift.org domain, please make sure that you're using http, and the redirect to www and https will then be handled correctly
